global:
  scrape_interval: 10s #frecuencia con la que se recolectan las metricas

scrape_configs:
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb_exporter:9216"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:3000"]

