name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # Reemplaza con la rama principal de tu repositorio

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Loguearte en Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t maxmartinez29/docker-resolve-frontend:latest -f Frontend/Dockerfile ./Frontend

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push maxmartinez29/docker-resolve-frontend:latest
